import { useEffect, useMemo, useRef, useState } from "react";
import { AlignLeft, CalendarDays, Check, CheckCircle2, ChevronDown, Clock3, Download, File, Flag, Folder, Link2, MessageSquare, MoreHorizontal, Paperclip, Plus, Send, Tags, Trash2, UploadCloud, Users, X } from "lucide-react";
import { apiBlob, apiDownload, apiJson, apiUpload } from "../services/api";
import { Avatar, Modal, PriorityPip } from "./ui";
import { clipboardImageFiles, imageExtension } from "../lib/clipboard";

const statusNames={TODO:"A fazer",IN_PROGRESS:"Em andamento",DONE:"Concluído"}; const priorityNames={LOW:"Baixa",MEDIUM:"Média",HIGH:"Alta",URGENT:"Urgente"};
// Estrutura mantida para uma possível retomada futura. Enquanto a flag estiver falsa,
// comentários, formulários e contadores de conversa não aparecem na interface.
const COMMENTS_FEATURE_ENABLED = false;
function inputDate(value){if(!value)return "";const date=new Date(value);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;}
function toIso(value){return value?new Date(`${value}T18:00:00`).toISOString():null;}
function timeAgo(value){const seconds=Math.floor((Date.now()-new Date(value))/1000);if(seconds<60)return "agora";if(seconds<3600)return `há ${Math.floor(seconds/60)} min`;if(seconds<86400)return `há ${Math.floor(seconds/3600)} h`;return new Date(value).toLocaleDateString("pt-BR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"});}
export default function TaskModal({task,data,token,user,onClose,onChanged,notify}){
  const isNew=task.isNew; const baseTeam=isNew?(task.teamId||(data.teams.length===1?data.teams[0].id:null)):task.teamId; const [form,setForm]=useState({title:isNew?"":task.title,description:isNew?"":task.description||"",teamId:baseTeam||"",folderId:isNew?(task.folderId||""):task.folderId||"",status:isNew?(task.status||"TODO"):task.status,priority:isNew?"MEDIUM":task.priority,dueAt:isNew?"":inputDate(task.dueAt),assigneeIds:isNew?[user.id]:task.assignees.map(a=>a.user.id),tagIds:isNew?[]:task.tags.map(t=>t.tag.id)}); const [tab,setTab]=useState("details"); const [busy,setBusy]=useState(false); const [uploading,setUploading]=useState(false); const [subtask,setSubtask]=useState(""); const [comment,setComment]=useState(""); const fileRef=useRef(); const uploadLockRef=useRef(false);
  const current=isNew?null:data.tasks.find(t=>t.id===task.id)||task; const teamUsers=useMemo(()=>(data.teams.find(t=>t.id===Number(form.teamId))?.members.map(m=>m.user)||data.users).filter(person=>person.active),[data.teams,data.users,form.teamId]); const teamTags=data.tags.filter(t=>t.teamId===Number(form.teamId)); const folders=data.folders.filter(f=>!f.teamId||f.teamId===Number(form.teamId));
  async function refresh(){if(isNew)return;const result=await apiJson(`/tasks/${task.id}`,{token});onChanged(result);}
  async function save(){if(!form.title.trim()){notify("Dê um título à atividade.","error");return;}if(!form.teamId){notify("Selecione uma equipe.","error");return;}setBusy(true);try{const payload={...form,teamId:Number(form.teamId),folderId:form.folderId?Number(form.folderId):null,dueAt:toIso(form.dueAt)};const result=isNew?await apiJson("/tasks",{token,method:"POST",data:payload}):await apiJson(`/tasks/${task.id}`,{token,method:"PATCH",data:payload});onChanged(result);notify(isNew?"Atividade criada":"Alterações salvas");if(!isNew)onClose();}catch(e){notify(e.message,"error");}finally{setBusy(false);}}
  async function remove(){if(!confirm("Excluir esta atividade? Ela sairá das visões, mas o evento ficará no histórico."))return;try{await apiJson(`/tasks/${task.id}`,{token,method:"DELETE"});onChanged({id:task.id,deleted:true});notify("Atividade excluída");}catch(e){notify(e.message,"error");}}
  async function addSubtask(e){e.preventDefault();if(!subtask.trim())return;try{await apiJson(`/tasks/${task.id}/subtasks`,{token,method:"POST",data:{title:subtask}});setSubtask("");await refresh();}catch(e){notify(e.message,"error");}}
  async function toggleSub(item){try{await apiJson(`/subtasks/${item.id}`,{token,method:"PATCH",data:{completed:!item.completed}});await refresh();}catch(e){notify(e.message,"error");}}
  async function deleteSub(item){try{await apiJson(`/subtasks/${item.id}`,{token,method:"DELETE"});await refresh();}catch(e){notify(e.message,"error");}}
  async function addComment(e){e.preventDefault();if(!comment.trim())return;try{await apiJson(`/tasks/${task.id}/comments`,{token,method:"POST",data:{body:comment}});setComment("");await refresh();}catch(e){notify(e.message,"error");}}
  async function uploadFile(file,{pasted=false}={}){if(!file||uploadLockRef.current)return false;if(file.size>10*1024*1024){notify("O arquivo deve ter no máximo 10 MB.","error");return false;}uploadLockRef.current=true;setUploading(true);try{notify(pasted?"Anexando imagem colada…":"Enviando arquivo…");await apiUpload(`/tasks/${task.id}/attachments`,{token,file});await refresh();notify(pasted?"Print anexado":"Arquivo anexado");return true;}catch(err){notify(err.message,"error");return false;}finally{uploadLockRef.current=false;setUploading(false);}}
  async function upload(e){const file=e.target.files?.[0];await uploadFile(file);e.target.value="";}
  function pastedFile(source,index=0){const stamp=new Date().toISOString().replace(/[:.]/g,"-");return new File([source],`captura-${stamp}${index?`-${index+1}`:""}.${imageExtension(source.type)}`,{type:source.type});}
  async function uploadPastedImages(images){for(const [index,source] of images.entries()){await uploadFile(pastedFile(source,index),{pasted:true});}}
  async function readClipboardImages({silent=false}={}){if(!navigator.clipboard?.read){if(!silent)notify("O navegador bloqueou a leitura. Clique dentro da janela e use Ctrl+V.","error");return;}try{const items=await navigator.clipboard.read();const images=[];for(const item of items){const type=item.types.find(value=>value.startsWith("image/"));if(type)images.push(await item.getType(type));}if(!images.length){if(!silent)notify("Não há uma imagem pronta para colar.","error");return;}await uploadPastedImages(images);}catch{if(!silent)notify("Não foi possível ler o clipboard. Autorize o acesso no navegador ou use Ctrl+V.","error");}}
  async function handlePaste(event){if(isNew||uploadLockRef.current)return;const images=clipboardImageFiles(event.clipboardData);if(images.length){event.preventDefault();await uploadPastedImages(images);return;}const clipboardText=event.clipboardData?.getData?.("text")||"";if(!clipboardText)await readClipboardImages({silent:true});}
  async function handleDrop(event){event.preventDefault();if(uploading)return;const file=event.dataTransfer?.files?.[0];await uploadFile(file);}
  useEffect(()=>{if(isNew)return;const listener=event=>{void handlePaste(event);};document.addEventListener("paste",listener,true);return()=>document.removeEventListener("paste",listener,true);},[isNew,task.id,token]);
  async function download(file){try{await apiDownload(`/attachments/${file.id}/download`,{token,filename:file.originalName});}catch(err){notify(err.message,"error");}}
  const completed=current?.subtasks.filter(s=>s.completed).length||0; const progress=current?.subtasks.length?Math.round(completed/current.subtasks.length*100):0;
  return <Modal onClose={onClose} className="task-modal"><header className="modal-header"><div className="task-breadcrumb"><span style={{"--crumb":data.teams.find(t=>t.id===Number(form.teamId))?.color}}/>{data.teams.find(t=>t.id===Number(form.teamId))?.name||"Nova atividade"}<span>/</span>{isNew?"Criar":"AG-"+task.id}</div><div><button title="Copiar link" onClick={()=>{navigator.clipboard?.writeText(location.href+`?task=${task.id}`);notify("Link copiado")}}><Link2/></button>{!isNew&&<button title="Excluir" onClick={remove}><Trash2/></button>}<button onClick={onClose}><X/></button></div></header>
    <div className="modal-tabs"><button className={tab==="details"?"active":""} onClick={()=>setTab("details")}>Atividade</button>{!isNew&&COMMENTS_FEATURE_ENABLED&&<button className={tab==="conversation"?"active":""} onClick={()=>setTab("conversation")}>Conversa <span>{current.comments.length}</span></button>} {!isNew&&<button className={tab==="activity"?"active":""} onClick={()=>setTab("activity")}>Histórico <span>{current.activity.length}</span></button>}</div>
    {tab==="details"&&<div className="modal-body task-detail-body"><div className="task-editor"><div className="title-line"><button className={`large-status status-${form.status.toLowerCase()}`} onClick={()=>setForm(f=>({...f,status:f.status==="DONE"?"TODO":"DONE"}))}>{form.status==="DONE"&&<Check/>}</button><textarea rows="1" autoFocus={isNew} value={form.title} onChange={e=>setForm(f=>({...f,title:e.target.value}))} placeholder="O que precisa ser feito?"/></div><textarea className="description" value={form.description} onChange={e=>setForm(f=>({...f,description:e.target.value}))} placeholder="Adicione contexto, links ou detalhes importantes…"/>
      {!isNew&&<section className="subtasks"><header><h3>Etapas</h3><span>{progress}%</span></header><div className="progress-track"><span style={{width:`${progress}%`}}/></div>{current.subtasks.map(item=><div className="subtask" key={item.id}><button className={item.completed?"checked":""} onClick={()=>toggleSub(item)}>{item.completed&&<Check/>}</button><span className={item.completed?"done":""}>{item.title}</span><button className="sub-delete" onClick={()=>deleteSub(item)}><X/></button></div>)}<form className="subtask-add" onSubmit={addSubtask}><Plus/><input value={subtask} onChange={e=>setSubtask(e.target.value)} placeholder="Adicionar uma etapa…"/></form></section>}
      {!isNew&&<section className="attachments" onDragOver={event=>event.preventDefault()} onDrop={handleDrop}><header><h3>Anexos</h3><button className="paste-action" disabled={uploading} onClick={()=>readClipboardImages()}><kbd>Ctrl</kbd> + <kbd>V</kbd> Colar print</button><button disabled={uploading} onClick={()=>fileRef.current.click()}><UploadCloud/>{uploading?"Enviando…":"Enviar arquivo"}</button><input ref={fileRef} hidden type="file" onChange={upload}/></header>{current.attachments.length?<div className="attachment-grid">{current.attachments.map(file=><button key={file.id} className={file.mimeType.startsWith("image/")?"image-attachment":""} onClick={()=>download(file)}><AttachmentThumbnail file={file} token={token}/><div><strong>{file.originalName}</strong><small>{(file.size/1024).toFixed(0)} KB · {timeAgo(file.createdAt)}</small></div><Download/></button>)}</div>:<p className="attachment-empty"><Paperclip/>Envie, arraste ou cole uma imagem com Ctrl+V · até 10 MB.</p>}</section>}
    </div><aside className="task-properties"><h3>Propriedades</h3><Property icon={<Users/>} label="Responsáveis"><div className="multi-select">{teamUsers.map(person=><button key={person.id} className={form.assigneeIds.includes(person.id)?"selected":""} onClick={()=>setForm(f=>({...f,assigneeIds:f.assigneeIds.includes(person.id)?f.assigneeIds.filter(id=>id!==person.id):[...f.assigneeIds,person.id]}))}><Avatar user={person} size="xs"/>{person.displayName}{form.assigneeIds.includes(person.id)&&<Check/>}</button>)}</div></Property>
      <Property icon={<Clock3/>} label="Status"><select value={form.status} onChange={e=>setForm(f=>({...f,status:e.target.value}))}>{Object.entries(statusNames).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></Property>
      <Property icon={<Flag/>} label="Prioridade"><select value={form.priority} onChange={e=>setForm(f=>({...f,priority:e.target.value}))}>{Object.entries(priorityNames).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></Property>
      <Property icon={<CalendarDays/>} label="Prazo"><input type="date" value={form.dueAt} onChange={e=>setForm(f=>({...f,dueAt:e.target.value}))}/></Property>
      <Property icon={<Users/>} label="Equipe"><select value={form.teamId} onChange={e=>setForm(f=>({...f,teamId:e.target.value,folderId:"",assigneeIds:[user.id],tagIds:[]}))}><option value="" disabled>Selecione uma equipe</option>{data.teams.map(team=><option key={team.id} value={team.id}>{team.name}</option>)}</select></Property>
      <Property icon={<Folder/>} label="Pasta"><select value={form.folderId} onChange={e=>setForm(f=>({...f,folderId:e.target.value}))}><option value="">Sem pasta</option>{folders.map(folder=><option key={folder.id} value={folder.id}>{folder.name}</option>)}</select></Property>
      <Property icon={<Tags/>} label="Tags"><div className="tag-options">{teamTags.map(tag=><button key={tag.id} style={{"--tag":tag.color}} className={form.tagIds.includes(tag.id)?"selected":""} onClick={()=>setForm(f=>({...f,tagIds:f.tagIds.includes(tag.id)?f.tagIds.filter(id=>id!==tag.id):[...f.tagIds,tag.id]}))}>{tag.name}</button>)}</div></Property>
    </aside></div>}
    {COMMENTS_FEATURE_ENABLED&&tab==="conversation"&&<div className="conversation"><div className="comment-stream">{current.comments.length?current.comments.map(item=><article key={item.id}><Avatar user={item.author}/><div><header><strong>{item.author.displayName}</strong><time>{timeAgo(item.createdAt)}</time></header><p>{item.body}</p></div></article>):<div className="tab-empty"><MessageSquare/><h3>Comece a conversa</h3><p>Comentários mantêm decisões e contexto junto da atividade.</p></div>}</div><form onSubmit={addComment}><Avatar user={user}/><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Escreva um comentário…"/><button><Send/></button></form></div>}
    {tab==="activity"&&<div className="timeline">{current.activity.map((event,index)=><article key={event.id}><div className="timeline-rail"><span className={`event-dot event-${event.action.toLowerCase()}`}>{event.action==="STATUS_CHANGED"?<CheckCircle2/>:<Clock3/>}</span>{index<current.activity.length-1&&<i/>}</div><div><p><strong>{event.actor?.displayName||"Sistema"}</strong> {event.summary}</p><time>{timeAgo(event.createdAt)}</time></div></article>)}</div>}
    {tab==="details"&&<footer className="modal-footer">{!isNew&&<span>Criada por <strong>{current.creator.displayName}</strong> · {timeAgo(current.createdAt)}</span>}<div><button className="secondary" onClick={onClose}>Cancelar</button><button className="primary" onClick={save} disabled={busy}>{busy?"Salvando…":isNew?"Criar atividade":"Salvar alterações"}</button></div></footer>}
  </Modal>;
}
function Property({icon,label,children}){return <div className="property"><label>{icon}{label}</label>{children}</div>}
function AttachmentThumbnail({file,token}){const [source,setSource]=useState("");useEffect(()=>{if(!file.mimeType.startsWith("image/"))return;let active=true;let objectUrl="";apiBlob(`/attachments/${file.id}/download`,{token}).then(blob=>{if(!active)return;objectUrl=URL.createObjectURL(blob);setSource(objectUrl);}).catch(()=>undefined);return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl);};},[file.id,file.mimeType,token]);if(source)return <span className="attachment-preview"><img src={source} alt={`Prévia de ${file.originalName}`}/></span>;return <span><File/></span>;}
