import { Fragment, useEffect, useMemo, useState } from "react";
import { CalendarDays, ChevronLeft, ChevronRight, CircleUserRound, Folder, Grid3X3, Inbox, LayoutList, LogOut, Menu, Plus, Search, Settings2, Trash2, UserRound, X } from "lucide-react";
import { useAuth } from "../components/AuthProvider";
import { apiJson } from "../services/api";

const ROLE_LABELS = { USER: "Colaborador", SUPERVISOR: "Supervisor", COORDINATOR: "Coordenador", ADMIN: "Administrador" };
import { Avatar, AvatarStack, EmptyState, PriorityPip, StatusButton, Toast } from "../components/ui";
import TaskModal from "../components/TaskModal";
import AdminModal from "../components/AdminModal";
import UserAnalytics from "../components/UserAnalytics";
import { matchesTaskScope, nextStatus, resolveTeamContext } from "../lib/taskUtils";

const statusNames={TODO:"A fazer",IN_PROGRESS:"Em andamento",DONE:"Concluído"};
const statusOrder=["TODO","IN_PROGRESS","DONE"];
const monthNames=["janeiro","fevereiro","março","abril","maio","junho","julho","agosto","setembro","outubro","novembro","dezembro"];
const isoDate=(value)=>value?new Date(value):null;
function periodBounds(mode, anchor){ const start=new Date(anchor); start.setHours(0,0,0,0); if(mode==="week"){ const day=(start.getDay()+6)%7; start.setDate(start.getDate()-day); const end=new Date(start); end.setDate(end.getDate()+7); return [start,end]; } start.setDate(1); const end=new Date(start); end.setMonth(end.getMonth()+1); return [start,end]; }
function periodLabel(mode, anchor){ const [start,end]=periodBounds(mode,anchor); if(mode==="month") return `${monthNames[start.getMonth()]} ${start.getFullYear()}`; const last=new Date(end); last.setDate(last.getDate()-1); return `${start.getDate()} ${monthNames[start.getMonth()].slice(0,3)} — ${last.getDate()} ${monthNames[last.getMonth()].slice(0,3)}`; }
function dueLabel(value){ if(!value)return "Sem prazo"; const date=new Date(value); const today=new Date(); today.setHours(0,0,0,0); const tomorrow=new Date(today); tomorrow.setDate(today.getDate()+1); if(date<today)return `Atrasada · ${date.toLocaleDateString("pt-BR",{day:"2-digit",month:"short"})}`; if(date<tomorrow)return "Hoje"; return date.toLocaleDateString("pt-BR",{day:"2-digit",month:"short"}); }

export default function WorkspacePage(){
  const {token,user,logout}=useAuth(); const [data,setData]=useState({tasks:[],teams:[],users:[],folders:[],tags:[]}); const [loading,setLoading]=useState(true); const [scope,setScope]=useState("mine"); const [view,setView]=useState("list"); const [period,setPeriod]=useState("week"); const [anchor,setAnchor]=useState(new Date()); const [search,setSearch]=useState(""); const [selected,setSelected]=useState(null); const [quick,setQuick]=useState(""); const [quickBusy,setQuickBusy]=useState(false); const [toast,setToast]=useState(null); const [admin,setAdmin]=useState(false); const [sidebar,setSidebar]=useState(false); const [folderForm,setFolderForm]=useState(false); const [analyticsUserId,setAnalyticsUserId]=useState(null);
  async function load(){ setLoading(true); try{setData(await apiJson("/bootstrap",{token}));}catch(e){setToast({type:"error",message:e.message});}finally{setLoading(false);} }
  useEffect(()=>{load();},[]);
  useEffect(()=>{if(loading)return;if(scope.startsWith("team:")&&!data.teams.some(team=>`team:${team.id}`===scope))setScope("mine");if(scope.startsWith("folder:")&&!data.folders.some(folder=>`folder:${folder.id}`===scope))setScope("mine");},[data.teams,data.folders,loading,scope]);
  function notify(message,type="ok"){setToast({message,type});setTimeout(()=>setToast(null),3000);}
  function replaceTask(task){setData(current=>({...current,tasks:current.tasks.map(item=>item.id===task.id?task:item)}));setSelected(current=>current?.id===task.id?task:current);}
  async function patchTask(taskId,change){ const previous=data.tasks.find(t=>t.id===taskId); if(previous) replaceTask({...previous,...change}); try{const updated=await apiJson(`/tasks/${taskId}`,{token,method:"PATCH",data:change});replaceTask(updated);return updated;}catch(e){if(previous)replaceTask(previous);notify(e.message,"error");} }
  function cycle(task){patchTask(task.id,{status:nextStatus(task.status)});}
  const visible=useMemo(()=>{ const [start,end]=periodBounds(period,anchor); const query=search.trim().toLocaleLowerCase("pt-BR"); return data.tasks.filter(task=>{
    if(!matchesTaskScope(task,scope,user.id))return false;
    if(query&&!`${task.title} ${task.description||""} ${task.tags.map(t=>t.tag.name).join(" ")}`.toLocaleLowerCase("pt-BR").includes(query))return false;
    if(task.dueAt){const due=isoDate(task.dueAt); if(due<start||due>=end)return false;} return true;
  });},[data.tasks,scope,search,period,anchor,user.id]);
  const scopeTitle=scope==="mine"?"Minhas atividades":scope.startsWith("team:")?(data.teams.find(t=>t.id===Number(scope.split(":")[1]))?.name||"Equipe"):(data.folders.find(f=>f.id===Number(scope.split(":")[1]))?.name||"Pasta");
  const selectedFolder=scope.startsWith("folder:")?data.folders.find(folder=>folder.id===Number(scope.split(":")[1])):null;
  const activeTeamId=resolveTeamContext(scope,data.folders,data.teams);
  const activeTeam=scope.startsWith("team:")?data.teams.find(team=>team.id===activeTeamId):null;
  const [periodStart,periodEnd]=periodBounds(period,anchor);
  const expandedTeamId=scope.startsWith("team:")?Number(scope.split(":")[1]):selectedFolder?.teamId||null;
  const counts={pending:visible.filter(t=>t.status!=="DONE").length,done:visible.filter(t=>t.status==="DONE").length};
  function movePeriod(direction){setAnchor(value=>{const next=new Date(value);if(period==="week")next.setDate(next.getDate()+direction*7);else next.setMonth(next.getMonth()+direction);return next;});}
  async function addQuick(e){e.preventDefault();if(!quick.trim()||quickBusy)return; if(!activeTeamId){notify("Selecione uma equipe antes de criar a atividade.","error");return;} setQuickBusy(true);try{const task=await apiJson("/tasks",{token,method:"POST",data:{title:quick,teamId:activeTeamId,folderId:selectedFolder?.id||null}});setData(current=>({...current,tasks:[...current.tasks,task]}));setQuick("");notify("Atividade criada");}catch(err){notify(err.message,"error");}finally{setQuickBusy(false);}}
  async function addFolder(name){if(!activeTeamId)return;try{const folder=await apiJson("/folders",{token,method:"POST",data:{name,color:"#d9a441",teamId:activeTeamId}});setData(current=>({...current,folders:[...current.folders,folder]}));setFolderForm(false);notify("Pasta criada");}catch(e){notify(e.message,"error");}}
  async function deleteFolder(folder,event){event.stopPropagation();if(!confirm(`Excluir a pasta “${folder.name}”? As atividades continuarão disponíveis na equipe.`))return;try{await apiJson(`/folders/${folder.id}`,{token,method:"DELETE"});setData(current=>({...current,folders:current.folders.filter(item=>item.id!==folder.id),tasks:current.tasks.map(task=>task.folderId===folder.id?{...task,folderId:null,folder:null}:task)}));if(scope===`folder:${folder.id}`)setScope(`team:${folder.teamId}`);notify("Pasta excluída");}catch(e){notify(e.message,"error");}}
  function startNew(initial={}){setSelected({isNew:true,...initial,teamId:initial.teamId||activeTeamId||undefined,folderId:initial.folderId||(selectedFolder?.id||undefined)});}
  function openTask(task){task?.isNew?startNew(task):setSelected(task);}
  function openScope(value){setScope(value);if(!value.startsWith("team:")&&view==="users")setView("list");setFolderForm(false);setSidebar(false);}
  function openUserView(){const members=(activeTeam?.members||[]).map(member=>member.user);setSearch("");setAnalyticsUserId(current=>members.some(person=>person.id===current)?current:(members.some(person=>person.id===user.id)?user.id:(members[0]?.id||null)));setView("users");}
  return <div className="app-shell">
    <aside className={`sidebar ${sidebar?"is-open":""}`}><div className="side-top"><div className="app-brand"><img src="/omega-logo-branco.png" alt="Omega"/><strong>Agenda</strong><small>OMEGA</small></div><button className="mobile-close" onClick={()=>setSidebar(false)}><X/></button></div>
      <nav className="side-nav"><button className={scope==="mine"?"active":""} onClick={()=>openScope("mine")}><Inbox/>Minhas atividades<span>{data.tasks.filter(t=>t.status!=="DONE"&&t.assignees.some(a=>a.user.id===user.id)).length}</span></button>
      <div className="nav-label">Equipes</div>{data.teams.map(team=><Fragment key={team.id}><button className={(scope===`team:${team.id}`||selectedFolder?.teamId===team.id)?"active":""} onClick={()=>openScope(`team:${team.id}`)}><i className="team-dot" style={{background:team.color}}/><span className="trim">{team.name}</span><span>{data.tasks.filter(t=>t.teamId===team.id&&t.status!=="DONE").length}</span></button>{expandedTeamId===team.id&&<div className="team-folder-tree"><div className="team-tree-label"><span>Pastas</span><button onClick={()=>setFolderForm(value=>!value)} aria-label="Nova pasta"><Plus/></button></div>{data.folders.filter(folder=>folder.teamId===team.id).map(folder=><div className="folder-nav-row" key={folder.id}><button className={scope===`folder:${folder.id}`?"active":""} onClick={()=>openScope(`folder:${folder.id}`)}><Folder style={{color:folder.color}}/><span className="trim">{folder.name}</span></button><button className="folder-delete" onClick={(event)=>deleteFolder(folder,event)} title="Excluir pasta"><Trash2/></button></div>)}{!data.folders.some(folder=>folder.teamId===team.id)&&!folderForm&&<span className="tree-empty">Nenhuma pasta</span>}{folderForm&&<form className="inline-folder" onSubmit={(e)=>{e.preventDefault();addFolder(e.currentTarget.elements.name.value)}}><input name="name" autoFocus placeholder="Nome da pasta"/><button><Plus/></button></form>}</div>}</Fragment>)}</nav>
      <div className="side-bottom">{user.role==="ADMIN"&&<button onClick={()=>setAdmin(true)}><Settings2/>Administração</button>}<div className="user-chip"><Avatar user={user}/><div><strong>{user.displayName}</strong><span>{ROLE_LABELS[user.role] || "Colaborador"}{user.role!=="ADMIN"&&user.teams.length?` · ${user.teams.map(t=>t.name).join(" · ")}`:""}</span></div>{import.meta.env.DEV&&<button onClick={logout} title="Sair"><LogOut/></button>}</div></div>
    </aside>
    <main className="workspace"><header className="topbar"><button className="mobile-menu" onClick={()=>setSidebar(true)}><Menu/></button><div className="search"><Search/><input value={search} disabled={view==="users"} onChange={e=>setSearch(e.target.value)} placeholder={view==="users"?"Análise consolidada por usuário":"Buscar atividade, tag ou pessoa…"}/><kbd>⌘ K</kbd></div><button className="top-icon"><CalendarDays/></button><Avatar user={user}/></header>
      <section className="content"><div className="content-heading"><div><span className="eyebrow">{new Date().toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long"})}</span><h1>{scopeTitle}</h1><p><strong>{counts.pending}</strong> pendentes · {counts.done} concluídas neste período</p></div><button className="new-task" onClick={()=>startNew()}><Plus/> Nova atividade</button></div>
      <div className="toolbar"><div className="view-switch"><button className={view==="list"?"active":""} onClick={()=>setView("list")}><LayoutList/>Lista</button><button className={view==="kanban"?"active":""} onClick={()=>setView("kanban")}><Grid3X3/>Kanban</button>{activeTeam&&<button className={view==="users"?"active":""} onClick={openUserView}><UserRound/>Por usuário</button>}</div><div className="period-nav"><button onClick={()=>movePeriod(-1)}><ChevronLeft/></button><button className="period-label" onClick={()=>setAnchor(new Date())}>{periodLabel(period,anchor)}</button><button onClick={()=>movePeriod(1)}><ChevronRight/></button></div><div className="period-switch"><button className={period==="week"?"active":""} onClick={()=>setPeriod("week")}>Semana</button><button className={period==="month"?"active":""} onClick={()=>setPeriod("month")}>Mês</button></div></div>
      {loading?<div className="task-skeleton">{[1,2,3,4].map(i=><span key={i}/>)}</div>:view==="list"?<TaskList tasks={visible} cycle={cycle} select={openTask} quick={quick} setQuick={setQuick} addQuick={addQuick} quickBusy={quickBusy}/>:view==="kanban"?<Kanban tasks={visible} cycle={cycle} select={openTask} move={(task,status)=>patchTask(task.id,{status})}/>:<UserAnalytics team={activeTeam} tasks={data.tasks} start={periodStart} end={periodEnd} period={period} selectedUserId={analyticsUserId} onSelectUser={setAnalyticsUserId} onOpenTask={openTask}/>}</section>
    </main>
    {selected&&<TaskModal task={selected} data={data} token={token} user={user} onClose={()=>setSelected(null)} onChanged={(task)=>{ if(task.deleted){setData(c=>({...c,tasks:c.tasks.filter(t=>t.id!==task.id)}));setSelected(null);}else if(data.tasks.some(t=>t.id===task.id))replaceTask(task);else{setData(c=>({...c,tasks:[...c.tasks,task]}));setSelected(task);} }} notify={notify}/>} {admin&&<AdminModal data={data} token={token} currentUserId={user.id} onClose={()=>setAdmin(false)} onChanged={load} notify={notify}/>}<Toast toast={toast} onClose={()=>setToast(null)}/>
  </div>;
}

function TaskList({tasks,cycle,select,quick,setQuick,addQuick,quickBusy}){ const groups=[{key:"late",title:"Atrasadas",test:t=>t.status!=="DONE"&&t.dueAt&&new Date(t.dueAt)<new Date(new Date().setHours(0,0,0,0))},{key:"active",title:"Em foco",test:t=>t.status!=="DONE"},{key:"done",title:"Concluídas",test:t=>t.status==="DONE"}]; const used=new Set(); return <div className="list-view">{groups.map(group=>{const items=tasks.filter(t=>group.test(t)&&!used.has(t.id));items.forEach(t=>used.add(t.id));if(!items.length&&group.key!=="active")return null;return <section className="task-group" key={group.key}><div className="group-title"><h3>{group.title}</h3><span>{items.length}</span><div/></div>{items.map(task=><TaskRow key={task.id} task={task} cycle={cycle} select={select}/>)}{group.key==="active"&&<form className="quick-add" onSubmit={addQuick}><Plus/><input value={quick} onChange={e=>setQuick(e.target.value)} placeholder="Digite e pressione Enter para criar uma atividade…"/><span>{quickBusy?"Criando…":"ENTER"}</span></form>}</section>})}{!tasks.length&&<EmptyState icon={<CircleUserRound/>} title="Tudo tranquilo por aqui" text="Nenhuma atividade corresponde a este período."/>}</div>; }
function TaskRow({task,cycle,select}){const subDone=task.subtasks.filter(s=>s.completed).length;return <button className={`task-row ${task.status==="DONE"?"is-done":""}`} onClick={()=>select(task)}><StatusButton status={task.status} onClick={()=>cycle(task)}/><div className="task-main"><strong>{task.title}</strong><div className="task-meta"><span className={`due ${task.dueAt&&new Date(task.dueAt)<new Date()&&task.status!=="DONE"?"late":""}`}><CalendarDays/>{dueLabel(task.dueAt)}</span>{task.subtasks.length>0&&<span>{subDone}/{task.subtasks.length} etapas</span>}<span>{task.team.name}</span></div></div><div className="tag-list">{task.tags.slice(0,2).map(({tag})=><span key={tag.id} style={{"--tag":tag.color}}>{tag.name}</span>)}</div><AvatarStack assignees={task.assignees}/><PriorityPip priority={task.priority}/><ChevronRight className="row-arrow"/></button>;}
function Kanban({tasks,cycle,select,move}){const [over,setOver]=useState(null);return <div className="kanban">{statusOrder.map(status=>{const items=tasks.filter(t=>t.status===status);return <section key={status} className={`kanban-column column-${status.toLowerCase()} ${over===status?"is-over":""}`} onDragOver={e=>{e.preventDefault();setOver(status)}} onDragLeave={()=>setOver(null)} onDrop={e=>{e.preventDefault();setOver(null);const task=tasks.find(t=>t.id===Number(e.dataTransfer.getData("task")));if(task&&task.status!==status)move(task,status)}}><header><i/><h3>{statusNames[status]}</h3><span>{items.length}</span><button><Plus/></button></header><div className="kanban-cards">{items.map(task=><article key={task.id} className="kanban-card" draggable onDragStart={e=>{e.dataTransfer.setData("task",task.id);e.dataTransfer.effectAllowed="move"}} onClick={()=>select(task)}><div className="card-tags">{task.tags.map(({tag})=><span key={tag.id} style={{"--tag":tag.color}}>{tag.name}</span>)}<PriorityPip priority={task.priority}/></div><h4>{task.title}</h4>{task.description&&<p>{task.description}</p>} {task.subtasks.length>0&&<div className="check-progress"><span style={{width:`${task.subtasks.filter(s=>s.completed).length/task.subtasks.length*100}%`}}/><small>{task.subtasks.filter(s=>s.completed).length}/{task.subtasks.length}</small></div>}<footer><span className={task.dueAt&&new Date(task.dueAt)<new Date()&&task.status!=="DONE"?"late":""}><CalendarDays/>{dueLabel(task.dueAt)}</span><AvatarStack assignees={task.assignees}/></footer></article>)}</div><button className="column-add" onClick={()=>select({isNew:true,status})}><Plus/>Adicionar atividade</button></section>})}</div>}
